// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjksznmbXv8VSbOtZUompI3ET1l21J6MQ',
    appId: '1:963210367786:web:e2d5115526c6d6b9e70453',
    messagingSenderId: '963210367786',
    projectId: 'expense-tracker-7717c',
    authDomain: 'expense-tracker-7717c.firebaseapp.com',
    storageBucket: 'expense-tracker-7717c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPq40jKdhRDkY7GDsqwlX51bFSWzEJa24',
    appId: '1:963210367786:android:413a05db780808ebe70453',
    messagingSenderId: '963210367786',
    projectId: 'expense-tracker-7717c',
    storageBucket: 'expense-tracker-7717c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEEmMg49QBb131iCH9TqiNa9DebbL6mqg',
    appId: '1:963210367786:ios:4772d69116427a26e70453',
    messagingSenderId: '963210367786',
    projectId: 'expense-tracker-7717c',
    storageBucket: 'expense-tracker-7717c.appspot.com',
    iosClientId: '963210367786-qhrvbliaa0aulqnnpvc33bb3i8f2s4mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEEmMg49QBb131iCH9TqiNa9DebbL6mqg',
    appId: '1:963210367786:ios:4772d69116427a26e70453',
    messagingSenderId: '963210367786',
    projectId: 'expense-tracker-7717c',
    storageBucket: 'expense-tracker-7717c.appspot.com',
    iosClientId: '963210367786-qhrvbliaa0aulqnnpvc33bb3i8f2s4mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
